apiVersion: v1
kind: Secret
metadata:
  name: gov-portal-secrets
  namespace: gov-portal
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production"
  DB_PASSWORD: "secure_password"
  REDIS_PASSWORD: "redis_password"
  ENCRYPTION_KEY: "NmwhLfg17m48JFJWwjy_WuLgKWHRaiXINcRS4VTsRcw="
  ENCRYPTION_KEY_SECONDARY: "Bat4VIl8HGodbO6rF8qDAdtHx2EFGy_EQO1-QSiL0NQ="
